name: Build and test

on:
  pull_request:
  push:
    paths-ignore:
    - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version:
          - 4.11.x
          - 4.12.x
          - 4.13.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update `apt`
        run: sudo apt-get update

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@master
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - run: opam install ocamlformat=0.22.4

      - name: Check autoformatting
        run: eval $(opam env) && dune build @fmt

      - run: opam install . --deps-only --with-test

      - name: Build code
        run: eval $(opam env) && make

      - name: Run tests
        run: eval $(opam env) && make test

      - name: Code coverage to codecov
        run: |
          eval $(opam env)
          rm . -name '*.coverage' | xargs rm -f
          dune runtest --instrument-with bisect_ppx --force
          bisect-ppx-report send-to Codecov
